version: "3.8"
services:
  django-backend-db:
    image: kartoza/postgis:12.1
    container_name: django-backend-db
    ports:
      - "5432:5432"
    environment:
      - DEFAULT_ENCODING=UTF8
      - DEFAULT_COLLATION=C
      - DEFAULT_CTYPE=C
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DBNAME=django_db

  djang-backend-redis:
    image: redis:alpine3.13
    container_name: djang-backend-redis
    ports:
      - "6379:6379"