[tool.poetry]
name = "djangobackendprogramming"
version = "0.1.0"
description = "한빛미디어 기술서 DjangoBackendProgramming 학습용 예제 코드"
authors = ["SoungRyoul Kim <KimSoungRyoul@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.1"
Django = "^3.1.3"
djangorestframework = "^3.12.2"
django-filter = "^2.4.0"
drf-spectacular = "^0.11.1"
django-extensions = "^3.0.9"
drf-nested-routers = "^0.92.1"
mypy = "^0.790"
pre-commit = "^2.9.3"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pytest-django = "^3.10.0"
pytest-tipsi-django = "^2.6.0"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
